In [1]:
import torch

In [2]:
input_shape = (4,3,2,2)

In [3]:
sample = torch.rand(input_shape)

In [4]:
sample[0]

tensor([[[4.3239e-01, 4.8918e-01],
         [5.8226e-01, 1.8305e-01]],

        [[9.3113e-01, 9.2834e-04],
         [3.5506e-01, 4.5909e-01]],

        [[3.0494e-01, 6.8134e-01],
         [2.1149e-01, 5.3663e-01]]])

In [23]:
std, mean = torch.std_mean(sample)

## For Processed Weights

In [38]:
sample = torch.eye(2) * 0.5
sample[0][0] = 1
sample

tensor([[1.0000, 0.0000],
        [0.0000, 0.5000]])

In [39]:
sample == 0

tensor([[False,  True],
        [ True, False]])

In [40]:
sample == 1

tensor([[ True, False],
        [False, False]])

In [44]:
(sample != 0) & (sample != 1)

tensor([[False, False],
        [False,  True]])

In [45]:
sample[(sample != 0) & (sample != 1)]

tensor([0.5000])

In [49]:
mean.item()

0.4527348577976227